src/picropper/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import RedirectView, TemplateView

from . import views as v

app_name = 'picropper'

urlpatterns = [
    # path('', TemplateView.as_view(template_name="picropper/base.html")),
    path('', RedirectView.as_view(url="/image/list")),
    path('image/list', v.ImageList.as_view(), name='ImageList'),
    path('image/create', v.ImageCreate.as_view(), name='ImageCreate'),
    path('image/<int:pk>/', v.ImageDetail.as_view(), name='ImageDetail'),
]

src/website/urls.py
"""Picropper website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/dev/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from django_error_views.handlers import *  # noqa F401

from .misc import debug

sitemaps = {}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('err/', debug.ErrView.as_view(), name='err'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('picropper.urls')),
    path('filer/', include('filer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'debug_toolbar' in settings.INSTALLED_APPS:
    if settings.DEBUG or 'SHOW_TOOLBAR_CALLBACK' in settings.DEBUG_TOOLBAR_CONFIG:
        import debug_toolbar  # noqa: F402

        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]

src/picropper/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from filer.fields.image import FilerImageField


class Image(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'), on_delete=models.CASCADE, blank=True, null=True)
    ts = models.DateTimeField(auto_now=True)
    file = FilerImageField(null=True, blank=True, related_name="logo_company", on_delete=models.CASCADE)

    class Meta:
        default_related_name = "images"
        verbose_name = _('image')
        verbose_name_plural = _('images')

src/picropper/forms.py
# coding=utf-8
from django import forms
from django.utils.translation import get_language
from django.utils.translation import ugettext_lazy as _

from . import models


class TranslatedMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.trans(get_language())


class SampleModelForm(forms.ModelForm):
    class Meta:
        model = models.SampleModel
        fields = ('name',)
        labels = {
            'name': _('name'),
        }

src/picropper/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import resolve_url
from django_powerbank.views.auth import AuthenticatedView
from filer.models import Image
from pascal_templates import ListView
from pascal_templates.views import CreateView, DetailView


class ImageList(AuthenticatedView, ListView):
    template_name = "picropper/Image/list.html"
    model = Image
    paginate_by = 50


class ImageCreate(AuthenticatedView, CreateView):
    model = Image
    fields = ('name',)

    def get_success_url(self):
        return resolve_url("picropper:SampleDetail", self.object.pk)


class ImageDetail(AuthenticatedView, DetailView):
    template_name = "picropper/Image/detail.html"
    model = Image

    def get_context_data(self, **kwargs):
        from filer.models import ThumbnailOption
        options = ThumbnailOption.objects.all()
        # thumbnailer = self.object.file.easy_thumbnails_thumbnailer
        thumbnailer = self.object.easy_thumbnails_thumbnailer
        versions = [(option.name, thumbnailer.get_thumbnail(option.as_dict)) for option in options]
        return super().get_context_data(versions=versions, **kwargs)

src/picropper/templates/picropper/Image/detail.html
{% extends "base/layout/page.html" %}
{% load i18n static %}
{% block content %}
  <div class="container">
    <div class="pt-5">
      <h1>{{ object.name }}</h1>
      {% load thumbnail %}
      <div class="row">
        {% for name, version in versions %}
          <div class="card m-2" style="width: 300px">
            <img src="{{ version.url }}" height="300" width="300" class="card-img-top"/>
            <div class="card-body">
              <h5 class="card-title">
                <a href="{{ version.url }}" class="">{{ name }}</a>
              </h5>
              <a href="{{ version.url }}" class="btn btn-primary" download="{{ object.file.name }}">{% trans "Pobierz" %} {{ version.width }}x{{ version.height }}</a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

src/picropper/templates/picropper/Image/form.html
{% extends "base/layout/page.html" %}
{% load bootstrap i18n %}
{% block content %}
  <div class="container pt-5">
    <div class="col-md-6 offset-md-3">
      <form action="" method="post">
        <legend>{% trans "Dodaj obraz do przetworzenia" %}</legend>
        {% csrf_token %}
        <table>
          {{ form|bootstrap }}
        </table>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">{% trans "Dodaj obraz" %}</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/picropper/templates/picropper/Image/list.html
{% extends 'base/layout/page.html' %}
{% load i18n %}
{% block content %}
  <div class="container ">
    <div class="pt-5">
      <h1>{% trans "Obrazy" %}</h1>
      <div class="mt-5">
        {% for object in object_list %}
          {% load thumbnail %}
          {% thumbnail object.file 150x150 crop as thumb %}
          <a href="{% url 'picropper:ImageDetail' object.pk %}" class="mr-1 ml-1">
            <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" class="img-thumbnail rounded mt-1 mb-1"/>
          </a>
        {% empty %}
          <p>{% trans "No pictures here, please upload some" %}</p>
        {% endfor %}
        {% include "picropper/pagination.html" %}
      </div>
    </div>
  </div>
{% endblock %}

src/picropper/templates/picropper/base.html
{% extends "base/layout/page.html" %}
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

src/picropper/templates/picropper/pagination.html
{% load i18n %}
{% if is_paginated %}
  <nav class="">
    <div class="pagination-container">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="previous page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              {% trans 'Previous' %}
            </a>
          </li>
        {% endif %}
        {% for page in page_obj.pages %}
          {% if page %}
          <li class="{% if page_obj.number == page %}active{% endif %} page-item">
            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
          </li>
          {% else %}
            <li class=" page-item"><span class="page-link disabled">…</span></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="next page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              {% trans 'Next' %}
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endif %}

templates/base/layout/alerts.html
<section id="alerts">
  {% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-warning alert-dismissible fade show mt-1">
        <div>
          {{ message|safe }}
        </div>
      </div>
    {% endfor %}
  {% endif %}
</section>

templates/base/layout/body.html
{% load assets %}
<!DOCTYPE html>
<!--
    (c)2018 Janusz Skonieczny
    Author: Janusz Skonieczny @wooyek
	Version: {{ system.website }} {{ system.revision }} {{ settings.ENVIRONMENT_NAME }}
-->
<html class="no-js" lang="{{ request.LANGUAGE_CODE }}"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{% block description %}{% endblock %}">
  <meta name="keywords" content="{% block keywords %}{% endblock %}"/>
  <meta name="author" content="{% block author %}{% endblock %}"/>
  <link rel="canonical" href="{{ settings.BASE_URL }}/{{ request.get_full_path }}"/>

  {% block assets %}
    {% assets "css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}" media="all">
    {% endassets %}
  {% endblock %}

  {% block css %}{% endblock %}{% block js %}{% endblock %}
  {% block head %}{% endblock %}
  {% block link %}{% endblock link %}
  {% block script %}{% endblock script %}

</head>
<body class="{{ request.resolver_match.url_name }} {% block body_class %}{% endblock %}" {% block body_attrs %}{% endblock %}
      data-locale="{{ request.LANGUAGE_CODE }}">
{% block body %}{% endblock %}
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
{% assets "js" %}
  <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% if settings.ENVIRONMENT_NAME %}<div class="watermark">{{ settings.ENVIRONMENT_NAME }} {{ system.website }} {{ system.revision }}</div>{% endif %}
</body>
</html>

templates/base/layout/footer.html
{% load i18n %}
<footer class="body-footer">
    <div class="container">
      <nav class="bg-dark navbar navbar-expand-sm navbar-dark">
      <ul class="navbar-nav mr-auto bordered">
          <li class="nav-item"><a class="nav-link" href="#">{% trans "Privacy Policy" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="#">{% trans "Contact" %}</a></li>
        </ul>
        <p class="navbar-text mb-0">{{ cookiecutter.copyright }} Copyright &copy; 2018. All rights reserved</p>
      </nav>
    </div>
</footer>

templates/base/layout/header.html
{% load i18n static %}
<header class="body-header">
  <div class="container bordered">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        Picropper
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav mt-2 mt-md-0">
{#            <li>#}
{#              <a class="nav-link" href="{% url 'picropper:ImageCreate' %}">#}
{#                <i class="fa fa-image"></i> {% trans "Create" %}#}
{#              </a>#}
{#            </li>#}
            <li>
              <a class="nav-link" href="/admin/filer/folder/">
                <i class="fa fa-upload"></i> {% trans "Upload" %}
              </a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'picropper:ImageList' %}">
                <i class="fa fa-list"></i> {% trans "List" %}
              </a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'admin:index' %}">
                <i class="fa fa-cog"></i> {% trans "Admin" %}
              </a>
            </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

templates/base/layout/page.html
{% extends "base/layout/body.html" %}
{% load i18n %}
{% block body %}
  {% include "base/layout/header.html" %}
  <main role="main" class="pb-5">
    <div class="container">
      {% include "base/layout/alerts.html" %}
    </div>
    {% block content %}
      <div class="container">
        <div class="jumbotron mb-5 mt-5">
          <h1>Lorem ipsum!</h1>
          <p class="lead">You are looking at a sample text in your website template `templates/base/layout/page.html`</p>
        </div>
      </div>
    {% endblock %}
  </main>
  {% include "base/layout/footer.html" %}
{% endblock %}